# _config.yml
# ... other configurations (title, theme, etc.)

exclude:
  - node_modules/
  - package.json # Optional, but good practice if it's a front-end project
  - package-lock.json # Optional, but good practice
  - Gemfile
  - Gemfile.lock
  - .gitignore
